### ISSUE TITLE
SVG export not working for multiple artboards

### ISSUE THREAD

**Issue by efuzul** [photopea/vectorpea#51]
I get an error when trying to export multiple artboards as SVGs: 
```
pp1718093804.js:10049 Uncaught TypeError: Cannot read properties of undefined (reading 'artboardRect')
    at Q.tN (pp1718093804.js:10049:57)
    at Object.C [as BL] (pp1718093804.js:5425:71)
    at b8.an.TC (pp1718093804.js:753:92)
    at fj.P9 (pp1718093804.js:14145:32)
    at ei.a (pp1718093804.js:11423:49)
    at iU.a (pp1718093804.js:11428:77)
    at bI.UP (pp1718093804.js:11501:95)
```
**Steps to reproduce:** 

1. Open project with multiple artboards
2. Export as -> SVG
3. Artboards option is checked
4. Save

![image](https://github.com/photopea/vectorpea/assets/7864665/1d2f6b4b-b300-42b0-a239-af59b8edcf02)

**Comment by photopea** [comment]
I have tried it and it seems to work fine. Could you maybe share a PSD with us, for which the error happens?

**Comment by photopea** [comment]
I have to close it, because nobody replied :(
